sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - PYTHONPATH=.
  - FLASK=0.12.2
install:
  - pip install Flask==$FLASK
  - pip install -r requirements.txt

script: python tests/unit_tests.py

after_success:
  - coveralls
